### ISSUE TITLE
Kubernetes doesn't garbage collect orphan config maps in leader election

### ISSUE THREAD

**Issue by jkobejs** [coralogix/zio-k8s#371]
In leader election config map lock is created with owner resourceType instead of kind for kind field
Because of that Kubernetes cannot garbage collect lock

Current behaviour:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: lock
  namespace: deafult
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: pods
    name: pod-5c56676969-m5dtr
    uid: 1052063d-a0ae-4639-bcdc-ecc4d0d440c5
```
Expected
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: lock
  namespace: deafult
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Pod
    name: pod-5c56676969-m5dtr
    uid: 1052063d-a0ae-4639-bcdc-ecc4d0d440c5
```
